export const sampleCategoryData = {
  properties: {
    name: "Properties",
    subcategories: [
      "New Builds",
      "Houses & Apartments for Rent",
      "Houses & Apartments for Sale",
      "Land & Plots for Rent",
      "Land & Plots for Sale",
      "Commercial Property for Rent",
      "Commercial Property for Sale",
      "Event Centers, Venues & Workstations",
      "Short Let Property",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
        name: "Luxury Apartment",
        description: "Modern 3-bedroom apartment in city center",
        price: 250000,
        location: "Lagos, Nigeria",
        timeAgo: "5 min ago",
        trending: true,
        isVerified: false,
        subcategory: "Houses & Apartments for Sale",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        name: "Beachfront Villa",
        description: "Spacious villa with ocean view",
        price: 450000,
        location: "Accra, Ghana",
        timeAgo: "10 min ago",
        trending: false,
        isVerified: true,
        subcategory: "Houses & Apartments for Sale",
      },
    ],
  },
  vehicles: {
    name: "Vehicles",
    subcategories: [
      "Cars",
      "Buses & Minibuses",
      "Heavy Equipment",
      "Motorcycles & Scooters",
      "Trucks & Trailers",
      "Vehicle Parts & Accessories",
      "Watercraft & Boats",
      "Automotive",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7",
        name: "Toyota Camry 2022",
        description: "Well-maintained sedan with low mileage",
        price: 25000,
        location: "Nairobi, Kenya",
        timeAgo: "15 min ago",
        trending: true,
        isVerified: true,
        subcategory: "Cars",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1502877338535-766e1452684a",
        name: "Honda Motorcycle",
        description: "2021 model in excellent condition",
        price: 3500,
        location: "Lagos, Nigeria",
        timeAgo: "20 min ago",
        trending: false,
        isVerified: false,
        subcategory: "Motorcycles & Scooters",
      },
    ],
  },
  gadgets: {
    name: "Gadgets",
    subcategories: [
      "Mobile Phones",
      "Smart Watches & Tablets",
      "Tablets",
      "Accessories for Mobile Phones & Tablets",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1511707171634-5f897206b8dd",
        name: "Smartphone Pro",
        description: "Latest model with 128GB storage",
        price: 800,
        location: "Cairo, Egypt",
        timeAgo: "30 min ago",
        trending: true,
        isVerified: true,
        subcategory: "Mobile Phones",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        name: "Gaming Laptop",
        description: "High-performance laptop with RTX graphics",
        price: 1200,
        location: "Johannesburg, South Africa",
        timeAgo: "45 min ago",
        trending: false,
        isVerified: true,
        subcategory: "Tablets", // Adjusted to a more fitting subcategory
      },
    ],
  },
  electronics: {
    name: "Electronics",
    subcategories: [
      "Accessories & Supplies",
      "Laptops & Computers",
      "TV & DVD Equipment",
      "Audio & Music Equipment",
      "Computer Accessories",
      "Computer Hardware",
      "Computer Monitors",
      "Headphones",
      "Networking Products",
      "Photo & Video Cameras",
      "Printers & Scanners",
      "Security & Surveillance",
      "Software",
      "Video Games",
      "Video Game Consoles",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1594041680534-e8c8cde93cd0",
        name: 'Smart TV 55"',
        description: "4K Ultra HD Smart LED Television",
        price: 600,
        location: "Lagos, Nigeria",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "TV & DVD Equipment",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1614330333219-7749df739a66",
        name: "Home Theater System",
        description: "5.1 surround sound system",
        price: 350,
        location: "Accra, Ghana",
        timeAgo: "2 hrs ago",
        trending: false,
        isVerified: false,
        subcategory: "Audio & Music Equipment",
      },
    ],
  },
   homeFurniture: {
    name: "Home Furniture & Appliances",
    subcategories: ["Furniture", "Home Appliances", "Kitchen & Dining"],
    products: [],
  },
  healthBeauty: {
    name: "Health & Beauty",
    subcategories: ["Bath & Body", "Fragrances", "Hair Beauty & Care", "Makeup", "Sexual Wellness", "Skincare", "Tools & Accessories", "Vitamins & Supplement"],
    products: [],
  },
  fashion: {
    name: "Fashion",
    subcategories: ["Bags", "Clothings", "Clothing Accessories", "Jewelry", "Shoes", "Watches", "Wedding Wear & Accessories" ],
    products: [],
  },
  sportsArts: {
    name: "Sports, Arts & Outdoors",
    subcategories: ["Arts & Crafts", "Books & Games", "Camping Gear", "CDs & DVD", "Musical Instrument & Gear","Sports Equipments",],
    products: [],
  },
  babiesKids: {
    name: "Babies & Kids",
    subcategories: ["Babies & kids Accessories", "Baby & Child Care", "Childrens Clothing","Childrens Furniture","Children’s Gear & Safety","Children Shoes","Maternity & Pregnancy","Prams & Strollers","Playground Equipment","Toys", ],
    products: [],
  },
  animalsPets: {
    name: "Animals & Pets",
    subcategories: ["Birds", "Dogs & Puppies", "Cats & Kittens", "Fish", "Pets Accessories","Other Animals"],
    products: [],
  },
  agricultureFood: {
    name: "Agriculture & Food",
    subcategories: ["Farm Machinery & Equipment", "Feed Supplement & Seeds", "Farm Animals", "Meals & Drinks", "Bulk farm Produce"],
    products: [],
  },
  equipmentTools: {
    name: "Equipment & Tools",
    subcategories: ["Industrial Ovens", "Manufacturing Equipments", "Manufacturing Materials", "Medical Supplies & Equipment", "Printing Equipments", "Food & Catering Equipments", "Safety Wear & Equipments", "Salon Equipments", "Stage Lighting & Equipments", "Stationary", "Store Equipments",],
    products: [],
  },
  repairConstruction: {
    name: "Repair & Construction",
    subcategories: ["Building Materials", "Doors", "Electrical Equipments", "Electrical Hand Tools", "Hand Tools", "Measuring & Layout Tools", "Plumbing & Water Supply", "Solar Energy", "Window", "Other Repair & Construction", ],
    products: [],
  },
};
