export const sampleCategoryData = {
  properties: {
    name: "Properties",
    subcategories: [
      "New Builds",
      "Houses & Apartments for Rent",
      "Houses & Apartments for Sale",
      "Land & Plots for Rent",
      "Land & Plots for Sale",
      "Commercial Property for Rent",
      "Commercial Property for Sale",
      "Event Centers, Venues & Workstations",
      "Short Let Property",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
        name: "Luxury Apartment",
        description: "Modern 3-bedroom apartment in city center",
        price: 250000,
        location: "Lagos, Nigeria",
        timeAgo: "5 min ago",
        trending: true,
        isVerified: false,
        subcategory: "Houses & Apartments for Sale",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        name: "Beachfront Villa",
        description: "Spacious villa with ocean view",
        price: 450000,
        location: "Accra, Ghana",
        timeAgo: "10 min ago",
        trending: false,
        isVerified: true,
        subcategory: "Houses & Apartments for Sale",
      },
    ],
  },
  vehicles: {
    name: "Vehicles",
    subcategories: [
      "Cars",
      "Buses & Mini buses",
      "Heavy Equipments",
      "Motocycles $ Scooters",
      "Trucks and Trailers",
      "Vehicle parts and Accessories",
      "Watercrafts $ Boats",
      "Automotive",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7",
        name: "Toyota Camry 2022",
        description: "Well-maintained sedan with low mileage",
        price: 25000,
        location: "Nairobi, Kenya",
        timeAgo: "15 min ago",
        trending: true,
        isVerified: true,
        subcategory: "Cars",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1502877338535-766e1452684a",
        name: "Honda Motorcycle",
        description: "2021 model with excellent condition",
        price: 3500,
        location: "Lagos, Nigeria",
        timeAgo: "20 min ago",
        trending: false,
        isVerified: false,
        subcategory: "Motorcycles",
      },
    ],
  },
  gadgets: {
    name: "Gadgets",
    subcategories: [
      "Mobile Phones",
      "Smart Watches and Ipads",
      "Tablets",
      "Accessories for Mobile phones and Tablets",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1511707171634-5f897206b8dd",
        name: "Smartphone Pro",
        description: "Latest model with 128GB storage",
        price: 800,
        location: "Cairo, Egypt",
        timeAgo: "30 min ago",
        trending: true,
        isVerified: true,
        subcategory: "Mobile Phones",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        name: "Gaming Laptop",
        description: "High-performance laptop with RTX graphics",
        price: 1200,
        location: "Johannesburg, South Africa",
        timeAgo: "45 min ago",
        trending: false,
        isVerified: true,
        subcategory: "Laptops",
      },
    ],
  },
  electronics: {
    name: "Electronics",
    subcategories: [
      "Accessories and Supplies",
      "Laptops & Computers",
      "TV & DVD Equipment",
      "Audio and Music Equipment",
      "Computer Accessories",
      "Computer Hardware",
      "Computer Monitors",
      "Headphones",
      "Networking Products",
      "Photo& Video Cameras",
      "Printers & Scanners",
      "Security & Surveillance",
      "Software",
      "Video Games",
      "Video Game Consoles"
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1594041680534-e8c8cde93cd0",
        name: "Smart TV 55\"",
        description: "4K Ultra HD Smart LED Television",
        price: 600,
        location: "Lagos, Nigeria",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Televisions",
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1614330333219-7749df739a66",
        name: "Home Theater System",
        description: "5.1 surround sound system",
        price: 350,
        location: "Accra, Ghana",
        timeAgo: "2 hrs ago",
        trending: false,
        isVerified: false,
        subcategory: "Home Audio",
      },
    ],
  },
  homeFurniture: {
    name: "Home Furniture & Appliances",
    subcategories: [
      "Furniture",
      "Garden Supplies",
      "Home Accessories",
      "Home Appliances",
      "Kitchen Appliances",
      "Kitchenware & Cookware",
      "Household Chemical"
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9ec",
        name: "Modern Sofa Set",
        description: "Comfortable 3-seater sofa",
        price: 450,
        location: "Nairobi, Kenya",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Sofas",
      },
    ],
  },
   healthBeauty: {
    name: "Health & Beauty",
    subcategories: [
      "Bath & Body",
      "Fragrances",
      "Hair Beauty & Care",
      "Makeup",
      "Sexual Wellness",
      "Skincare",
      "Tools & Accessories",
      "Vitamins & Supplement"
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9ec",
        name: "Modern Sofa Set",
        description: "Comfortable 3-seater sofa",
        price: 450,
        location: "Nairobi, Kenya",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Sofas",
      },
    ],
  },
   fashion: {
    name: "fashion",
    subcategories: [
      "Bags",
      "Clothings",
      "Clothing Accessories",
      "Jewelry",
      "Shoes",
      "Watches",
      "Wedding Wear & Accessories",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9ec",
        name: "Modern Sofa Set",
        description: "Comfortable 3-seater sofa",
        price: 450,
        location: "Nairobi, Kenya",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Sofas",
      },
    ],
  },
   sportsArts: {
    name: "Sports, Arts & Outdoors",
    subcategories: [
      "Arts & Crafts",
      "Books & Games",
      "Camping Gear",
      "CDs & DVD",
      "Musical Instrument & Gear",
      "Sports Equipments",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9ec",
        name: "Modern Sofa Set",
        description: "Comfortable 3-seater sofa",
        price: 450,
        location: "Nairobi, Kenya",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Sofas",
      },
    ],
  },
   babiesKids: {
    name: "Babies & Kids",
    subcategories: [
      "Arts & Crafts",
      "Books & Games",
      "Camping Gear",
      "CDs & DVD",
      "Musical Instrument & Gear",
      "Sports Equipments",
    ],
    products: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9ec",
        name: "Modern Sofa Set",
        description: "Comfortable 3-seater sofa",
        price: 450,
        location: "Nairobi, Kenya",
        timeAgo: "1 hr ago",
        trending: true,
        isVerified: true,
        subcategory: "Sofas",
      },
    ],
  },
};